### ISSUE TITLE
Invisible gradio icon on taskbar (tray)

### ISSUE THREAD

**Issue by armageddon51** [haecker-felix/gradio#126] opened 2016-12-27 21:30 UTC
When the "close to tray icon" option is selected and the program is close, an "icon" open up on the panel "tray" but is invisible. The mouse over reveal "click to restore". 
However, there is no need really because gradio integrate beautifully with the new drop down media window under the sound control icon. 

Linux Mint Cinnamon 18.1.

Thanks !

**Comment by crobe87** [comment] 2016-12-28 18:02
about tray icon not visible, duplicate of #123

**Comment by simonbcn** [comment] 2017-01-03 11:58
Same problem on Arch Linux

**Comment by PrzemekSkw** [comment] 2017-01-19 09:00
I have similar problem on Fedora 25, i'ts hard to see black tray icon on dark gnome-shell themes.

**Comment by vkotovv** [comment] 2017-05-04 12:04
Same for me: could not see the icon in the tray. Ubuntu 16.04, Mate environment 1.18

**Comment by vkotovv** [comment] 2017-05-04 12:11
Any plans for releasing 5.1 @haecker-felix ?

**Comment by haecker-felix** [comment] 2017-05-04 12:50
@vkotovv yep. But 5.1 is going to be 6.0.

**Comment by haecker-felix** [comment] 2017-06-16 20:41
The tray icon option got removed, because it is a deprecated technology. Just use the mpris panel, it has the same features.

**Closed by haecker-felix** 2017-06-16 20:41 UTC
Labels: Priority: Medium, Status: In work, Type: Bug

**Comment by vkotovv** [comment] 2017-06-19 08:12
@haecker-felix does Mate have mpris panel? how do I use that?

**Comment by haecker-felix** [comment] 2017-06-19 17:30
I don't use mate, I'm not sure, but just look in the audio panel. There will be an extra panel if you run gradio. There you see the current title and can stop/pause it.
