### ISSUE TITLE
Ideas and more

### ISSUE THREAD

**Issue by grindhold** [haecker-felix/gradio#101] opened 2016-11-06 14:54 UTC
Hi, Felix.

I've lately had some ideas of my own on how to design an internet radio application for gnome. A few weeks ago i stumbled over your project, when checking out the latest development efforts in the Vala world, and I am a happy user of the development version ever since. Thanks so far.
I see a lot of potential in your project. Therefore I decided to share my records and design-ideas with the gradio project instead of starting my own one, because I have a lot of other stuff to code already. I hope you like them as much as I do.

Radio View
--------------

![design_gnome_radio](https://i.imgur.com/nBsKhmQ.png)

You can see here my design for a "radio"-view.

  * Tuner bar resembles an UKW (UHF) - style frequency search bar
  * Tuner knob moves the frequency search bar
  * When the search bar is not on a valid radio station, the radio will blend in static noise, just like real analog radios.
  * Searchbar may be given glossy optics and eyecandy (may require some cairo knowledge)
  * The station can also be selected by clicking on the station tags under the searchbar.

The "WANT!"-Button
--------------------------

The second feature I suggest requires a little more in-depth knowledge of GStreamer. I suggest to have a "WANT"-Button that causes the program to save the currently played song onto disk. This is the more casual way to do what we nowadays probably do with streamripper. But we have to search for our song manually and throw out all the recorded songs that we do not want to. The program must herefor:

  * Have a gstreamer pipeline that takes the output of the streamsource and distributes it to a) the ouput sink to the soundcard and to a filesink that writes a temporary file on disk.
  * Have a button in the ui that sets a flag that designates that the user wants to save the currently played song
  * Whenever we detect that the "Currently Played" string changes, we need to check whether the flag has been checked or not. If yes, take the recorded tempfile, rename it to what the radiostation submitted as the songs name and save it into a user-defined folder ( ```~/music/``` would be nice as default ) then remove the tempfile and begin recording the current song to the tempfile.
  * When we tune in to a new radio station, the want!-button must be insensitive until the first song-change occurs. Otherwise we cannot deliver a fully-recorded song to the user.
  * The functionality to set the flag could also be exposed via DBus in order to have a shell-extension with a big graphic industrial grade WANT!-Buzzer :)

I hope you like the ideas on this. Maybe sometime I can manage to contribute, too.
I'm looking forward to your comments.

**Comment by haecker-felix** [comment] 2016-11-19 15:06
Sorry for the delayed answer. 

***Radio View***
Looks _very_ nice, but the problem is: Where I get the UKW data? Gradio is based on this database:
http://www.radio-browser.info/gui/#/

But an overview "view" like this, looks very nice. I'm experimenting with a button, which toggles the view into a overview mode which is smaller. But don't except this in the 5.x release. 

***Want Button***
This idea is VERY nice!! But there are some problems.

> 
When we tune in to a new radio station, the want!-button must be insensitive until the first song-change occurs. Otherwise we cannot deliver a fully-recorded song to the user.

A new song starts. You press the "want" button after 15 seconds. There are now 15 seconds missing. It think it is difficult to decide in the first five seconds if you want the song or not ;). The solution would be a time shift, but than is the stream doesn't "live" more.

> The functionality to set the flag could also be exposed via DBus in order to have a shell-extension with a big graphic industrial grade WANT!-Buzzer :)

I agree. There must be a button which is accessible from everywhere. Switching to gradio and press it, would be take to much time. 

> Therefore I decided to share  my records and design-ideas with the gradio project instead of starting my own one...
That is very nice. Feel free to contribute to gradio with your code ;). Gradio is currently a "one-man-project", that's why the progress is more than slow.

**Comment by grindhold** [comment] 2016-11-19 15:38
> A new song starts. You press the "want" button after 15 seconds. There are now 15 seconds missing. > It think it is difficult to decide in the first five seconds if you want the song or not ;). The solution would > be a time shift, but then the stream isn't "live" anymore.

In my concept **any** song is being recorded by default. If the WANT-button has been pressed during the song, gradio will save the recorded song to disk somewhere when the song completes. If not, it will simply drop the recorded data. The WANT-button is **not** a record-button. This way, we can avoid the problem described by you.

**Comment by grindhold** [comment] 2016-11-19 15:43
> Looks very nice, but the problem is: Where I get the UKW data? Gradio is based on this database:
http://www.radio-browser.info/gui/#/

I didn't intend to use real UKW-data (most of the channels are internet-only anyway). Just let the user move his favourite radio-channels on the frequency-bar as he sees fit.

**Comment by haecker-felix** [comment] 2016-11-19 16:07
> In my concept any song is being recorded by default. If the WANT-button has been pressed during the song, gradio will save the recorded song to disk somewhere when the song completes. If not, it will simply drop the recorded data. The WANT-button is not a record-button (others have done this, and it was crappy). This way, we can avoid the problem described by you.

Make much sense. 

> I didn't intend to use real UKW-data (most of the channels are internet-only anyway). Just let the user move his favourite radio-channels on the frequency-bar as he sees fit.

Mhm i think this is not so useful. It is more a "toy" than a feature. Let's see if can include you design ideas in the new overview page in the next versions (6.x +)

**Comment by grindhold** [comment] 2016-11-19 17:51
I am well aware that this is a toy-feature. It is the logical conclusion I drew from seeing other design efforts regarding GNOME-Core apps. Design simple apps that feel natural. It's the extra mile I'd go in order to deliver a tool that does not only does what it was meant to, but also to draw a little smile on the user's face ;)

**Comment by haecker-felix** [comment] 2016-11-19 18:19
Mhm you might be right. But there are other features that have a higher priority ;)

**Comment by grindhold** [comment] 2016-11-19 19:58
lol. don't worry. i never wrote "IMPLEMENT THIS NOW!!11!one!1eleven!1" ;)

**Comment by haecker-felix** [comment] 2016-11-19 20:07
Okay just wanted to say because there are some people who will start to cry if their feature wont implement within 2 hours :D

**Comment by haecker-felix** [comment] 2016-11-19 22:09
I close this issue, because it isn't a real issue / bug. Your ideas have been added to my todo list ;)

**Closed by haecker-felix** 2016-11-19 22:09 UTC
