### ISSUE TITLE
Settings schema 'de.haecker-felix.gradio' is not installed

### ISSUE THREAD

**Issue by drxspace** [haecker-felix/gradio#81] opened 2016-10-03 15:36 UTC
Hi again,

I'm coming back with another issue. I'm trying to run gradio but I'm getting these:
`** Message: main.vala:6: Starting Gradio version 5.0.0b2!

(gradio:12364): GLib-GIO-ERROR **: Settings schema 'de.haecker-felix.gradio' is not installed`

and then after run it again, these:

`** Message: main.vala:6: Starting Gradio version 5.0.0b2!

(gst-plugin-scanner:16093): GStreamer-WARNING **: Failed to load plugin '/usr/lib/gstreamer-1.0/libgstvulkan.so': libvulkan.so.1: cannot open shared object file: No such file or directory

(gst-plugin-scanner:16093): GStreamer-WARNING **: Failed to load plugin '/usr/lib/gstreamer-1.0/libgstzbar.so': libzbar.so.0: cannot open shared object file: No such file or directory

(gradio:16091): GLib-GIO-ERROR **: Settings schema 'de.haecker-felix.gradio' is not installed

Trace/breakpoint trap (core dumped)`

A little help would be appreciate
Thank you

**Comment by haecker-felix** [comment] 2016-10-03 15:46
How did you installed gradio? Are you sure you run "sudo make install"?

**Comment by drxspace** [comment] 2016-10-03 16:46
I'm using a custom package that is
`...
prepare() {
	cd "${srcdir}/${_gitname}/"
	"${srcdir}/${_gitname}/"autogen.sh
}

build() {
	cd "${srcdir}/${_gitname}/"
#	"${srcdir}/${_gitname}/"autogen.sh
	make
}

package() {
	cd "${srcdir}/${_gitname}/"
	make DESTDIR="${pkgdir}" install
}`
but if I follow the steps you have in README.md I'm getting for `make`
`Making all in data
make[1]: Entering directory '~/Downloads/gradio/data'
Makefile:746: *** missing separator.  Stop.
make[1]: Leaving directory '~/Downloads/gradio/data'
make: *** [Makefile:368: all-recursive] Error 1`
and for `sudo make install`
`[sudo] password for me:  
Making install in data
make[1]: Entering directory '~/Downloads/gradio/data'
Makefile:746: *** missing separator.  Stop.
make[1]: Leaving directory '~/Downloads/gradio/data'
make: *** [Makefile:368: install-recursive] Error 1`

**Comment by haecker-felix** [comment] 2016-10-04 05:07
Duplicate of #78.

**Closed** 2016-10-04 05:07 UTC
