### ISSUE TITLE
'disappearing' tray icon on ubuntu 16.04

### ISSUE THREAD

**Issue by arooni** [haecker-felix/gradio#196] opened 2017-08-15 01:14 UTC
I hit in settings 'close to tray icon' ; hit close; and app keeps running but I don't see any tray icon.  I'm running unity.  

Any idea why?  

Also I was thinking of opening a separate issue but I have dark theme selected and closed/reopened the app no luck.  

In any case this is still way better than radiotray.  Thanks!

**Comment by haecker-felix** [comment] 2017-08-16 12:30
The dark theme isn't supported on the ambiance theme of unity. Not an issue of gradio itself. 

The tray icon issue is known. I'm working on it.

**Comment by haecker-felix** [comment] 2017-08-16 12:42
Duplicate of #176.

**Closed by haecker-felix** 2017-08-16 12:42 UTC
