### ISSUE TITLE
What's the purpose of "Enable background playback"?

### ISSUE THREAD

**Issue by simonbcn** [haecker-felix/gradio#130] opened 2017-01-03 12:11 UTC
If I activate `Enable background playback` and I deactivate `Close to tray icon`, when I close the gradio window, it stops playback and close the application. ❓ 
If I activate `Enable background playback` and I activate `Close to tray icon`, when I close the gradio window, it remains playback but there isn't tray icon #126. ‼️ 

If I deactivate `Enable background playback` and I activate `Close to tray icon`, when I close the gradio window, it remains playback but there isn't tray icon #126. ‼️ 
If I deactivate `Enable background playback` and I deactivate `Close to tray icon`, when I close the gradio window, it stops playback and close the application. ✔️ 

It seems that `Enable background playback` does nothing by itself without `Close to tray icon`.

**Comment by haecker-felix** [comment] 2017-01-09 17:27
Enable background playback -> If a stations is being played, hide the window and resume the playback in the "background"

I will improve the descriptions of these feature, to make it more understandable.

**Comment by simonbcn** [comment] 2017-01-09 17:38
I still don't understand the feature. "Hide the window" is "close to tray"?

**Comment by simonbcn** [comment] 2017-01-09 23:29
This comment is about this too: https://github.com/haecker-felix/gradio/issues/109#issuecomment-263111345
I think `Enable background playback` is redundant. If I enabled `close to tray icon` the `enable background playback` is implicit. In fact, when `close to tray icon` is disabled the `enable background playback` does nothing if I close the window.

**Comment by haecker-felix** [comment] 2017-02-10 13:11
duplicate of #117

**Closed by haecker-felix** 2017-02-10 13:11 UTC
Labels: Priority: High, Status: In work, Type: Feature Request
