### ISSUE TITLE
Gnome permanent notification shows wrong song name

### ISSUE THREAD

**Issue by pabgan** [haecker-felix/Gradio#342] opened 2018-08-29 15:45 UTC
The permanent notification in the Gnome notification center that tells you the Station, current song and has playback buttons does not show correctly the name of the song.

## Expected Behavior

Line should read:
Artist - Song name

## Current Behavior

Line reads:
Artist - text="Song name"
See screenshot: ![gradio - notification bug](https://user-images.githubusercontent.com/2458157/44798866-e340c000-abb2-11e8-9a65-f81c2e962e2d.png)

## Steps to Reproduce

1. Open Gradio.
2. Play a random station.

## Detailed Description

```
% lsb_release -a                                                                           
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	Fedora
Description:	Fedora release 28 (Twenty Eight)
Release:	28
Codename:	TwentyEight

% flatpak info de.haeckerfelix.gradio                                                      !10006
Referencia: app/de.haeckerfelix.gradio/x86_64/stable
ID: de.haeckerfelix.gradio
Arquitectura: x86_64
Rama: stable
Origen: flathub
Collection ID: org.flathub.Stable
Date: 2018-08-19 07:55:45 +0000
Subject: Use 3.28 branch of the GNOME runtime (04bce224)
Commit: 39a2ee5142c37a05277cae9d69779371e1e74937a638c4b85ffaf32cc4027a22
Parent: df959ee3cb1e6c2d8e3f7928f6d886e5d5d72489508ee46a784e64426d17ada3
Localización: /var/lib/flatpak/app/de.haeckerfelix.gradio/x86_64/stable/39a2ee5142c37a05277cae9d69779371e1e74937a638c4b85ffaf32cc4027a22
Tamaño de la instalación: 1,4 MB
Runtime: org.gnome.Platform/x86_64/3.28
Sdk: org.gnome.Sdk/x86_64/3.28
```

**Comment by haecker-felix** [comment] 2018-08-29 18:35
duplicate of #315

**Closed by haecker-felix** 2018-08-29 18:35 UTC
