### ISSUE TITLE
In Ubuntu 16.04 no tray icon (indicator) and no dark design

### ISSUE THREAD

**Issue by VosaXalo** [haecker-felix/gradio#123] opened 2016-12-27 18:08 UTC
Hi,
I have found out a couple of bugs in the last version 5.0:
1) turning on the option for a dark design doesn't change the interface theme
2) turning on "Close to tray icon" doesn't work. There is no Ubuntu Unity indicator. I have to use the system monitor to stop gradio.

I'm using Ubuntu 16.04 LTS 64bit

Regards

**Comment by zajc** [comment] 2016-12-28 08:21
I can confirm. Ubuntu 16.04, no tray icon and no dark theme.

**Comment by crobe87** [comment] 2016-12-28 18:04
Running ubuntu 16.04 with i3 wm:
- dark theme works fine
- no icon showing on tray, but the square space is there and I can click on it to restore to fullscreen.

**Comment by kj800x** [comment] 2016-12-29 09:25
Linux Mint 18.1 with Cinnamon (Dark Mint-Y theme)

- Dark Theme button has no effect for me (regardless of the setting, gradio uses my system's Dark Mint-Y theme).
- When gradio is closed (with close to tray icon enabled), space for a tray icon is created, but no icon actually shows up.

I'm actually a little confused about what certain settings are supposed to do. I expected that when I have "Enable background playback" on, and "Close to tray icon" off, gradio would continue to play if I closed it (but not if I "quit" it from the menu). Instead, if I close gradio (even with "Enable background playback" on) the music stops. I don't know if this is a bug, or I'm just not understanding these settings right.

**Comment by haecker-felix** [comment] 2016-12-29 12:21
1. Not every desktop environment supports a dark theme. For example Unity doesn't.  This is not a bug of gradio itself. 

2. Yes this is a bug. The icon is invisible. ( #126 ) But you can click the gradio icon from the app starter,  and the old session should restore.

**Closed by haecker-felix** 2016-12-29 12:21 UTC
