### ISSUE TITLE
wider than my screen

### ISSUE THREAD

**Issue by gungoksu** [haecker-felix/gradio#124] opened 2016-12-27 19:00 UTC
The app is wider than my screen. width does not fit. No way in settings to make it use less width.

**Comment by crobe87** [comment] 2016-12-28 18:11
details? device, screen resolution, operating system, window manager...

**Comment by kj800x** [comment] 2016-12-29 09:37
I'm on Linux Mint 18.1 with Cinnamon (screen resolution 1366 x 768).

Although the window fits on my screen, It's minimum size seems too large.
I've played around with a pixel ruler and the smallest I can get the window is about ~1130 x ~280. This is  wider than 800x600, which is a uncommon but still used screen resolution.

Normally I am able to dock windows to half of the screen by dragging them to one side, but that doesn't work with gradio. I think that's because the minimum width is greater than half of my screen.

This is the window as small as I can get it. As you can see, it takes up most of my screen width.
![Screenshot of gradio](https://cloud.githubusercontent.com/assets/1657142/21540800/fbaab410-cd7f-11e6-9aea-3dc20ac0138f.png)

**Comment by stroobandt** [comment] 2016-12-29 17:46
This is affecting me too. I need to be able to resize to 996px width.
This issue can be merged with my enhancement proposal https://github.com/haecker-felix/gradio/issues/129

**Comment by haecker-felix** [comment] 2017-02-10 12:48
duplicate of #129

**Closed by haecker-felix** 2017-02-10 12:48 UTC
