### ISSUE TITLE
Merge Add / Search pages toghether? 

### ISSUE THREAD

**Issue by dasnoopy** [haecker-felix/gradio#243] opened 2017-11-12 05:09 UTC
just a thought..
...after all, Add  and Search does, more or less the same thing  showing almost same results  
(excluding the possibility to add a new station in the global database)

**Comment by haecker-felix** [comment] 2017-11-12 09:47
First of all: Yes i understand your thoughts.

But there is a big problem. The discover section. 
![bildschirmfoto vom 2017-11-12 10-42-07](https://user-images.githubusercontent.com/6001248/32697678-35e32cdc-c796-11e7-81d6-8c17a76a7afa.png)

I have learned, that people absolutely want this view at a glance. I've got a lot of critics about the missing discover section in Gradio 6.0. 

I want to remove the add page, it hate it. But i don't find a proper way to integrate it into the search page, without making a big mess. The main problem: Search != Discover.

**Comment by dasnoopy** [comment] 2017-11-12 18:48
don't kown if this could be acceptable  but  if you are thinking  to remove the add page, SEARCH could be renamed as DISCOVER like in the previous version of gradio, then discover options could be showed in the extended search menu. 

Something like this ugly mockup:
![discover](https://user-images.githubusercontent.com/296922/32702038-eb672d8e-c7e0-11e7-889e-5d60ed1a6262.png)

Related to how many discovered stations to show you could use the same  dconf options to limit the  max search results (or you could be make this option "public" and add it the settings page)

finally , add a new public station  station could be a simple entry in the options menu

**Comment by haecker-felix** [comment] 2017-11-12 19:32
Yeah the main problem is the discover section. Everything else shouldn't be a big thing.

Your mockup shows 3 buttons, like in version 6 of Gradio (Add Page). The problem is, the userbase want to see the 3 groups directly like in Gradio 5.0 or earlier. They want a "AppStore"-like view. For example the Google PlayStore shows some recommend apps directly on their start page.

And this view isn't possible with those three buttons (Unfortunately not, this would be too easy...), because the userbase want to see the three groups directly on one page.

Please don't get me wrong, i know this is a stupid "problem".

**Comment by dasnoopy** [comment] 2017-11-14 06:31
thanks for the explanation .. based on your thoughts,  having separate add and search page is the best choice at the moment.

Feel free to close this issue if you consider it suitable

**Comment by dasnoopy** [comment] 2017-11-14 19:03
in the meantime, last try  ( I promise ;-) 
![addsearpage](https://user-images.githubusercontent.com/296922/32798981-97dde7ba-c976-11e7-842d-6b530de5ea30.png)

 I think mockup is quite explanatory

**Comment by haecker-felix** [comment] 2017-11-14 19:20
Feel free to send more mockups :)

This one I find very interesting. It looks nice, but some questions:

- Why a "Sort:" popover?  Is there a reason why there shouldn't be a "More" button in the corresponding group (like actually)

- "Sort By:" should be in the hamburger menu, but i think there it looks better, the problem is, the app would look inconsistent (sometime it's in hamburger menu, sometime it's somewhere else)

**Comment by dasnoopy** [comment] 2017-11-14 19:41
I just add "**sort by"** popover because the mockup is based on the current "Add page" where hamburger menu is not availble in the header bar  (while in search page is available) and maybe  to avoid some click :)

about "**show**" popover  maybe a little explations could help :)

**1)** show all station ( = search)
**2)**  show  directly  in the page 15-20 results from all three group  (just like now,  when you enter in the add page for the first time) 
**3,4,5)** show all stations filtered by specific group, pretty much what the "more" button actually does ( I guess)

**Comment by haecker-felix** [comment] 2017-11-14 20:07
Looks very interesting. I'll think about it and get back to you.

**Comment by haecker-felix** [comment] 2017-11-15 17:40
The decision has been made: I will implement this feature for 7.0. The release date is moved back (if necessary).

**Comment by haecker-felix** [comment] 2017-11-17 19:33
Add page and search page -> merged 😄. Still needs a lot of polish, but the basics are working. 

![bildschirmfoto vom 2017-11-17 20-30-58](https://user-images.githubusercontent.com/6001248/32965239-40afeb3e-cbd6-11e7-8581-96b0f9b71f2b.png)

**Closed by haecker-felix** 2017-11-17 19:33 UTC

**Comment by dasnoopy** [comment] 2017-11-18 06:29
really nice implementation, as usual :)).. thank you so much
