### ISSUE TITLE
window size

### ISSUE THREAD

**Issue by gasinclair** [haecker-felix/gradio#142] opened 2017-01-23 11:43 UTC
i'm running gradio via linux mint 18.1 on my acer aspire one (kav10).  an excellent program with easy access to all the stations i've sought from home and abroad.  my only niggle is the inability to minimise the screen to fit on my ancient netbooks 1024x600 resolution, having to pull the window horizontally across the screen to access all features.

would it be possible to reduce the minimum window resizing to allow a better windowed experience on older devices?

keep up the good work.

**Comment by haecker-felix** [comment] 2017-01-29 09:43
duplicate of #129

**Closed by haecker-felix** 2017-01-29 09:43 UTC
