### ISSUE TITLE
On start fo gradio the audio volume is put on the max

### ISSUE THREAD

**Issue by tglman** [haecker-felix/gradio#227] opened 2017-09-26 15:54 UTC
Hi,

Each time I start gradio and I start to play a station the volume goes up to maximum, it doesn't happen after the first time, the environment is debian with gnome-shell.

Regards

**Comment by haecker-felix** [comment] 2017-11-06 16:32
Well, i cannot reproduce this bug. I hope this is now fixed with your pull request. Feel free to reopen this issue if the bug still persists.

**Closed by haecker-felix** 2017-11-06 16:32 UTC

**Comment by germanfr** [comment] 2018-03-28 09:31
Hey I'm experiencing this issue too, it's very annoying. Every time I open Gradio, when I click on a station it sets system volume to 100%. That pull request didn't solve anything for me. I'm on **Gradio 7.1** running on Cinnamon.

**Comment by germanfr** [comment] 2018-03-28 09:42
It seems to be related to #279 and that custom volume you explained there, because this happens too when you set the volume from the app slider.

If you move the slider above system volume it raises it (more or less) accordingly, but if you lower the volume from the app the system is unchanged. Without looking at the code, I would say that the fact that the app volume starts at 100% is the cause system volume raises to 100% too.
