### ISSUE TITLE
[Build error] too many arguments to function ‘gdk_pixbuf_save_to_stream_finish’

### ISSUE THREAD

**Issue by alex285** [haecker-felix/gradio#184] opened 2017-07-08 19:34 UTC
Meson: 0.41.1 / Arch Linux

/home/alex/Git/gradio/src/gradio-image-cache.vala: In function ‘gradio_image_cache_cache_image_co’:
/home/alex/Git/gradio/src/gradio-image-cache.vala:106:3: error: too many arguments to function ‘gdk_pixbuf_save_to_stream_finish’
        yield pixbuf.save_to_stream_async(fiostream.get_output_stream(), "png");
   ^    ~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/gdk-pixbuf-2.0/gdk-pixbuf/gdk-pixbuf.h:34:0,
                 from src/gradio@exe/gradio-image-cache.c:29:
/usr/include/gdk-pixbuf-2.0/gdk-pixbuf/gdk-pixbuf-core.h:512:10: note: declared here
 gboolean gdk_pixbuf_save_to_stream_finish (GAsyncResult  *async_result,
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[61/66] Compiling C object 'src/gradio@exe/src_gradio@exe_gradio-selection-toolbar.c.o'.
ninja: build stopped: subcommand failed.

**Comment by haecker-felix** [comment] 2017-07-08 19:50
duplicate of #182

**Closed by haecker-felix** 2017-07-08 19:50 UTC
