### ISSUE TITLE
Feature Request: Some way to sort Library

### ISSUE THREAD

**Issue by AinaSG** [haecker-felix/gradio#160] opened 2017-03-10 12:20 UTC
A way to sort the stations in your library could be nice. Sorry if this is already in there, I can't find it.

**Comment by cunei** [comment] 2017-03-12 18:16
Related to (or duplicate of) https://github.com/haecker-felix/gradio/issues/106, https://github.com/haecker-felix/gradio/issues/158

**Closed** 2017-03-12 18:21 UTC

**Comment by haecker-felix** [comment] 2017-03-28 15:31
duplicate of #106
